import React from "react";
import { Link } from "react-router-dom";
const Home = () => {
  return (
    <div className="dhiwise-navigation">
      <h1>Homepage</h1>
      <p className="headline">
        This project was generated By{" "}
        <a href="https://www.dhiwise.com">Dhiwise</a>. Quickly use below links
        to navigate through all pages.
      </p>
      <ul>
        <li>
          <Link to="/dhasboard">Dhasboard</Link>
        </li>
        <li>
          <Link to="/violationsone">ViolationsOne</Link>
        </li>
        <li>
          <Link to="/myprofile">MyProfile</Link>
        </li>
        <li>
          <Link to="/changepassword">ChangePassword</Link>
        </li>
        <li>
          <Link to="/violations">Violations</Link>
        </li>
        <li>
          <Link to="/history">History</Link>
        </li>
        <li>
          <Link to="/violationfines">ViolationFines</Link>
        </li>
        <li>
          <Link to="/violationsmapview">ViolationsMapView</Link>
        </li>
        <li>
          <Link to="/signin">Signin</Link>
        </li>
        <li>
          <Link to="/forgotpassword">ForgotPassword</Link>
        </li>
        <li>
          <Link to="/changepasswordone">ChangePasswordOne</Link>
        </li>
      </ul>
    </div>
  );
};
export default Home;
